[user]
name = "hitentandon"
display-name = "Hiten-Tandon"
initial-password = "123456"
sudo = true                   # Always have at least one user with super privleges
shell = "nushell"
de = "cosmic"                    # TODO: Valid Options include: KDE, Gnome, Cosmic, Xfce, Cinnamon
# wm = Hyprland               # TODO: Valid Options include: Hyprland, i3, awesome, swaywm

[system]
dm = "cosmic-greeter"                # TODO: gdm, cosmic-greeter
time-zone = "Asia/Kolkata"

[misc]
flatpak-enabled = true
